# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AVLicensePlate' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'IQKeyboardManager'
    pod 'SVProgressHUD', '1.1.3'
    pod 'FMDB'
end

